version: "3.9"
services:
  whatsthemove:
    restart: always
    build: ../wtmAPI
    container_name: whatsthemove
    ports:
      - "5051:5050"
    depends_on:
      - wtmdb
    environment:
      - apiport=5053
      - BROKER_SERVER_ADDRESS=broker:29092
      - WTM_TOPIC=WTM=Topic
  whatsthemove2:
    restart: always
    build: ../wtmAPI
    container_name: whatsthemove
    ports:
      - "5051:5050"
    depends_on:
      - wtmdb
    environment:
      - apiport=5053
      - BROKER_SERVER_ADDRESS=broker:29092
      - WTM_TOPIC=WTMTopic
  wtmdb:
    image: "mongo:latest"
    container_name: "wtmdb"
    ports:
      - "5010:27017"
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
  broker:
    restart: always
    image: confluentinc/cp-kafka:7.3.0
    container_name: broker
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
  nginx:
    build: ../nginx
    ports:
      - "5053:80"
    depends_on:
      - whatsthemove
      - whatsthemove2
  mqservice:
    build: ../MQService
    ports:
      - "5054:5054"
    depends_on:
      - broker
      - zookeeper
      - whatsthemove
      - whatsthemove2
      - nginx
